name: bayes_course

channels:
  - conda-forge
dependencies:
  - python
  - arviz
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - lxml
  - matplotlib
  - numpy
  - pandas
  - patsy
  - pip
  - pymc
  - pydot
  - python-graphviz
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - xlrd
